import { useMemo, useState, useEffect } from "react";
import players from "./players.json";
import "./style.css";
const target={P:3,D:8,C:8,A:6};
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
export default function App(){
 const [owned,setOwned]=useState(()=>load('fc-owned',[])); const [rivals,setRivals]=useState(()=>load('fc-rivals',[]));
 const [selected,setSelected]=useState(players[0]); const [bid,setBid]=useState(players[0].suggested); const [q,setQ]=useState(''); const [role,setRole]=useState('ALL');
 const [manager,setManager]=useState(''); const [rivalPlayer,setRivalPlayer]=useState('');
 useEffect(()=>localStorage.setItem('fc-owned',JSON.stringify(owned)),[owned]); useEffect(()=>localStorage.setItem('fc-rivals',JSON.stringify(rivals)),[rivals]);
 const spent=owned.reduce((s,p)=>s+p.paid,0), remaining=1000-spent;
 const counts=useMemo(()=>owned.reduce((a,p)=>(a[p.role]=(a[p.role]||0)+1,a),{}),[owned]);
 const slots=Object.entries(target).reduce((s,[r,n])=>s+Math.max(0,n-(counts[r]||0)),0), reserve=Math.max(0,slots-1), spendable=Math.max(0,remaining-reserve);
 const need=Math.max(0,target[selected.role]-(counts[selected.role]||0));
 const rolePressure=need>=4?1.1:need<=1?.86:1, budgetPressure=remaining<250?.8:remaining>650?1.05:1;
 const hardMax=Math.min(Math.max(selected.quote,Math.round(selected.max*rolePressure*budgetPressure)),spendable);
 const verdict=bid<=hardMax*.82?'RILANCIA':bid<=hardMax?'ULTIMO RILANCIO':'LASCIA';
 const filtered=players.filter(p=>(role==='ALL'||p.role===role)&&`${p.name} ${p.team}`.toLowerCase().includes(q.toLowerCase()));
 const buy=()=>{if(bid<=remaining&&!owned.some(p=>p.id===selected.id)&&(counts[selected.role]||0)<target[selected.role])setOwned([...owned,{...selected,paid:bid}])};
 const addRival=()=>{if(manager.trim()&&rivalPlayer.trim()){setRivals([{id:Date.now(),manager:manager.trim(),player:rivalPlayer.trim()},...rivals]);setRivalPlayer('')}};
 const reset=()=>{if(confirm('Azzerare tutti i dati dell asta?')){setOwned([]);setRivals([])}};
 const exportState=()=>{const b=new Blob([JSON.stringify({owned,rivals},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='fantacalcio-asta.json';a.click();URL.revokeObjectURL(a.href)};
 const importState=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);setOwned(Array.isArray(d.owned)?d.owned:[]);setRivals(Array.isArray(d.rivals)?d.rivals:[])}catch{alert('File JSON non valido')}};r.readAsText(f)};
 return <div className="app"><header><div><small>✨ AI AUCTION ROOM</small><h1>Fantacalcio Live Copilot</h1><p>Lista 25, budget dinamico e decisioni rapide durante l'asta.</p></div><span className="league">Classic · 8 squadre · 1000 crediti · Mod. difesa e capitano</span></header>
 <section className="stats">{[['Budget',1000],['Spesi',spent],['Disponibili',remaining],['Slot mancanti',slots]].map(x=><div className="card stat" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</section>
 <main><section className="card list"><div className="filters"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cerca giocatore..."/><select value={role} onChange={e=>setRole(e.target.value)}><option value="ALL">Tutti</option>{Object.keys(target).map(r=><option key={r}>{r}</option>)}</select></div><div className="scroll">{filtered.map(p=><button className={selected.id===p.id?'player active':'player'} key={p.id} onClick={()=>{setSelected(p);setBid(p.suggested)}}><b>{p.name}</b><i>{p.role}</i><span>{p.team} · {p.tier} · FM {p.fm} · Tit. {p.starter}%</span></button>)}</div></section>
 <section className="card detail"><div className="title"><div><small>GIOCATORE IN ASTA</small><h2>{selected.name}</h2><p>{selected.team} · {selected.role} · {selected.tier}</p></div><span>Rischio {selected.risk}</span></div><div className="metrics">{[['Gol',selected.goals],['Assist',selected.assists],['MV',selected.mv],['FM',selected.fm]].map(x=><div key={x[0]}><b>{x[1]}</b><span>{x[0]}</span></div>)}</div><div className="metrics triple">{[['Quotazione',selected.quote],['Target',selected.suggested],['Max base',selected.max]].map(x=><div key={x[0]}><b>{x[1]}</b><span>{x[0]}</span></div>)}</div><label>Titolarità stimata <b>{selected.starter}%</b></label><progress max="100" value={selected.starter}/><div className="bid"><span>Offerta attuale</span><div><button onClick={()=>setBid(Math.max(1,bid-1))}>−</button><input type="number" min="1" value={bid} onChange={e=>setBid(+e.target.value||0)}/><button onClick={()=>setBid(bid+1)}>+</button></div></div><div className={'verdict '+verdict.replaceAll(' ','-').toLowerCase()}><h3>{verdict}</h3><b>MAX {hardMax}</b><p>{verdict==='LASCIA'?`Offerta oltre il tetto dinamico di ${hardMax}.`:`Non superare ${hardMax} crediti.`}</p></div><button className="buy" disabled={bid>remaining||owned.some(p=>p.id===selected.id)||(counts[selected.role]||0)>=target[selected.role]} onClick={buy}>🔨 Segna come acquistato a {bid}</button></section>
 <aside><section className="card"><h3>La mia rosa</h3><div className="roles">{Object.entries(target).map(([r,n])=><span key={r}><b>{counts[r]||0}/{n}</b>{r}</span>)}</div>{owned.length===0?<p className="muted">Nessun acquisto ancora.</p>:owned.map(p=><div className="row" key={p.id}><span>{p.name} <b>{p.paid}</b></span><button onClick={()=>setOwned(owned.filter(x=>x.id!==p.id))}>×</button></div>)}</section><section className="card"><h3>Rose avversarie</h3><input value={manager} onChange={e=>setManager(e.target.value)} placeholder="Fantallenatore"/><div className="inline"><input value={rivalPlayer} onChange={e=>setRivalPlayer(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addRival()} placeholder="Giocatore preso"/><button onClick={addRival}>+</button></div>{rivals.map(x=><div className="row" key={x.id}><small><b>{x.manager}</b> ha preso {x.player}</small></div>)}</section><section className="card tools"><button onClick={exportState}>Esporta JSON</button><label>Importa JSON<input hidden type="file" accept="application/json" onChange={importState}/></label><button className="danger" onClick={reset}>Reset asta</button></section></aside></main><footer>Dati da aggiornare manualmente. Fonte di riferimento: Fantacalcio.it. Progetto non affiliato a Fantacalcio.it.</footer></div>}
